# Generated by Django 3.0.6 on 2020-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('reg_no', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('speed', models.CharField(max_length=60)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
