# Generated by Django 3.0.6 on 2020-09-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20200927_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='registered_id',
            field=models.IntegerField(default=None),
        ),
    ]
