# Generated by Django 3.0.6 on 2020-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_activeuser_registered_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuser',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
